### ISSUE TITLE
Error: The 'sklearn' PyPI package is deprecated, use 'scikit-learn' rather than 'sklearn' for pip commands.

### ISSUE THREAD

**Issue by 0xdevalias** [glato/emerge#35]
**Describe the bug**

`pip install` fails due to error `The 'sklearn' PyPI package is deprecated, use 'scikit-learn' rather than 'sklearn' for pip commands.`
```
⇒  pip install emerge-viz

..snip..

Collecting sklearn
  Downloading sklearn-0.0.post1.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.

      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error

      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package

      If the previous advice does not cover your use case, feel free to report it at
      https://github.com/scikit-learn/sklearn-pypi-package/issues/new
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Describe your environment**
- Are you using the tool on macOS or linux? macOS
- Which Python version are you using? 
- Which browser (with version) are you using? N/A
- Are you scanning a public source code repository that you can provide? N/A
- If not - can you provide code snippets where or further information on the data that might be relevant for the bug? N/A

**To Reproduce**

```bash
pip install emerge-viz
```

**Expected behavior**

The tool installs correctly.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by TravisDart** [comment]
Fixed by #36

**Comment by 0xdevalias** [comment]
**Edit2:** I just relealised that #36 hasn't even been merged yet 😅 

<details>
<summary>Original Comment</summary>

Installed/up to date:
```
⇒  pip install -U emerge-viz
Requirement already satisfied: emerge-viz in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (1.4.0)
Requirement already satisfied: pycodestyle in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (2.9.1)
Requirement already satisfied: interrogate in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (1.5.0)
Requirement already satisfied: python-louvain in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (0.16)
Requirement already satisfied: coloredlogs in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (15.0.1)
Requirement already satisfied: py in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (1.11.0)
Requirement already satisfied: pyparsing in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (3.0.9)
Requirement already satisfied: wheel in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (0.38.4)
Requirement already satisfied: networkx in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (2.8.8)
Requirement already satisfied: pygraphviz in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (1.10)
Requirement already satisfied: tabulate in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (0.9.0)
Requirement already satisfied: numpy in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (1.23.3)
Requirement already satisfied: sklearn in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (0.0.post1)
Requirement already satisfied: pylint in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (2.15.9)
Requirement already satisfied: PyYAML in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (6.0)
Requirement already satisfied: prettytable in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (3.5.0)
Requirement already satisfied: autopep8 in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from emerge-viz) (1.7.0)
Requirement already satisfied: toml in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from autopep8->emerge-viz) (0.10.2)
Requirement already satisfied: humanfriendly>=9.1 in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from coloredlogs->emerge-viz) (10.0)
Requirement already satisfied: colorama in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from interrogate->emerge-viz) (0.4.6)
Requirement already satisfied: attrs in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from interrogate->emerge-viz) (22.2.0)
Requirement already satisfied: click>=7.1 in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from interrogate->emerge-viz) (8.1.3)
Requirement already satisfied: wcwidth in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from prettytable->emerge-viz) (0.2.5)
Requirement already satisfied: platformdirs>=2.2.0 in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from pylint->emerge-viz) (2.5.2)
Requirement already satisfied: tomli>=1.1.0 in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from pylint->emerge-viz) (2.0.1)
Requirement already satisfied: tomlkit>=0.10.1 in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from pylint->emerge-viz) (0.11.6)
Requirement already satisfied: astroid<=2.14.0-dev0,>=2.12.13 in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from pylint->emerge-viz) (2.12.13)
Requirement already satisfied: mccabe<0.8,>=0.6 in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from pylint->emerge-viz) (0.7.0)
Requirement already satisfied: dill>=0.2 in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from pylint->emerge-viz) (0.3.6)
Requirement already satisfied: isort<6,>=4.2.5 in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from pylint->emerge-viz) (5.11.4)
Requirement already satisfied: wrapt<2,>=1.11 in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from astroid<=2.14.0-dev0,>=2.12.13->pylint->emerge-viz) (1.14.1)
Requirement already satisfied: lazy-object-proxy>=1.4.0 in /Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages (from astroid<=2.14.0-dev0,>=2.12.13->pylint->emerge-viz) (1.8.0)
```

But gets the following error: `ModuleNotFoundError: No module named 'sklearn'`:
```
⇒  emerge -h
Traceback (most recent call last):
  File "/Users/devalias/.pyenv/versions/3.10.2/bin/emerge", line 5, in <module>
    from emerge.main import run
  File "/Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages/emerge/main.py", line 8, in <module>
    from emerge.appear import Emerge
  File "/Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages/emerge/appear.py", line 27, in <module>
    from emerge.config import Configuration
  File "/Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages/emerge/config.py", line 25, in <module>
    from emerge.metrics.tfidf.tfidf import TFIDFMetric
  File "/Users/devalias/.pyenv/versions/3.10.2/lib/python3.10/site-packages/emerge/metrics/tfidf/tfidf.py", line 12, in <module>
    from sklearn.exceptions import NotFittedError
ModuleNotFoundError: No module named 'sklearn'
```

---

**Edit:** Though looking at the following, the latest released version is `1.4.0` from October 2022, so I guess #36 may not have been released yet?

- https://pypi.org/project/emerge-viz/#history

</details>

**Comment by glato** [comment]
@TravisDart @0xdevalias Just merged. Sorry for the delay & @TravisDart thanks for the PR, will create a new release until tomorrow.

**Comment by 0xdevalias** [comment]
Awesome! Thanks for that :)
