### ISSUE TITLE
exception following the README: ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by sglebs** [glato/emerge#57]
**Describe the bug**

Exception when trying to install & use following the README (pip alternative).

**Describe your environment**

- MacBook Pro 2023, M3
- Python 3.12.4

**To Reproduce**

1.  python3 -m venv ./venv
2. source  ./venv/bin/activate 
3. pip install emerge-viz  
4. emerge -a swift      

The console will print a stack trace and the culprit:

ModuleNotFoundError: No module named 'pkg_resources'

```
Traceback (most recent call last):
  File "..../venv/bin/emerge", line 5, in <module>
    from emerge.main import run
  File "..../venv/lib/python3.12/site-packages/emerge/main.py", line 8, in <module>
    from emerge.appear import Emerge
  File "..../venv/lib/python3.12/site-packages/emerge/appear.py", line 24, in <module>
    from emerge.languages.pyparser import PythonParser
  File "..../venv/lib/python3.12/site-packages/emerge/languages/pyparser.py", line 16, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Expected behavior**

No exception.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Daendaralus** [comment]
I just encountered this issue as well. I was, however, following the guide to install it from source instead (Windows 11, Python 3.12.0) 
Running `pip install --upgrade setuptools` fixed it for me.

**Comment by sglebs** [comment]
> I just encountered this issue as well. I was, however, following the guide to install it from source instead (Windows 11, Python 3.12.0) Running `pip install --upgrade setuptools` fixed it for me.

I can confirm that this fixes it for me too. Great tip, thanks for sharing!

**Comment by dundalek** [comment]
I also encountered this issue. With [uv](https://github.com/astral-sh/uv) it is also possible to run emerge without venv or prior installation using following one-liner:

```
uvx --from emerge-viz --with setuptools --with pip emerge
```
